name: Cats Wearing Gold Chains
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aaa3ab'
    - '#140e12'
    - '#c22200'
    - '#e1512d'
  brandStrength: 0.602263739798218
  lightness: 0.12027146108448505
  saturation: 0.8575384409632534
  rhythmicContrast: 0.6552142768632621
purpose: []
