name: Cats Wearing Gold Chains
favicon: null
layout_spectrum: 0.9815017732325941
typography_spectrum: 0.7949081873521209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.602263739798218
  lightness: 0.12027146108448505
  saturation: 0.8575384409632534
  rhythmicContrast: 0.6552142768632621
purpose: []
